dashboard/urls.py
from django.conf.urls import url
from . import views

app_name = 'dashboard'

urlpatterns = [
	
	# Login & Logout
	url(r'^login$', views.LoginView.as_view(), name='login'),
	url(r'^logout$', views.LogoutView.as_view(), name='logout'),

	# Dashboard index
	url(r'^$', views.DashboardIndex.as_view(), name='index'),

	# Notices
	url(r'^notices/$', views.NoticeListView.as_view(), name='notices-list'),
	url(r'^notices/create$', views.NoticeCreateView.as_view(),name='notices-create'),
	url(r'^notices/(?P<pk>\d+)/update$', views.NoticeUpdateView.as_view(),name='notices-update'),
	url(r'^notices/(?P<pk>\d+)/delete$', views.NoticeDeleteView.as_view(),name='notices-delete'),
	url(r'notices/detail/(?P<pk>[0-9]+)/$', views.NoticeDetailView.as_view(), name='notices-detail'),

	# Press release
	url(r'^press-releases/$', views.PressReleaseListView.as_view(), name='press-releases-list'),
	url(r'^press-releases/create$', views.PressReleaseCreateView.as_view(),name='press-releases-create'),
	url(r'^press-releases/(?P<pk>\d+)/update$', views.PressReleaseUpdateView.as_view(),name='press-releases-update'),
	url(r'^press-releases/(?P<pk>\d+)/delete$', views.PressReleaseDeleteView.as_view(),name='press-releases-delete'),
	url(r'press-releases/detail/(?P<pk>[0-9]+)/$', views.PressReleaseDetailView.as_view(), name='press-releases-detail'),

	# Bid
	url(r'^bids/$', views.BidListView.as_view(), name='bids-list'),
	url(r'^bids/create$', views.BidCreateView.as_view(),name='bids-create'),
	url(r'^bids/(?P<pk>\d+)/update$', views.BidUpdateView.as_view(),name='bids-update'),
	url(r'^bids/(?P<pk>\d+)/delete$', views.BidDeleteView.as_view(),name='bids-delete'),
	url(r'bids/detail/(?P<pk>[0-9]+)/$', views.BidDetailView.as_view(), name='bids-detail'),

	# Publications
	url(r'^publications/$', views.PublicationListView.as_view(), name='publications-list'),
	url(r'^publications/create$', views.PublicationCreateView.as_view(),name='publications-create'),
	url(r'^publications/(?P<pk>\d+)/update$', views.PublicationUpdateView.as_view(),name='publications-update'),
	url(r'^publications/(?P<pk>\d+)/delete$', views.PublicationDeleteView.as_view(),name='publications-delete'),
	url(r'publications/detail/(?P<pk>[0-9]+)/$', views.PublicationDetailView.as_view(), name='publications-detail'),

	# Policies
	url(r'^policies/$', views.PolicyListView.as_view(), name='policies-list'),
	url(r'^policies/create$', views.PolicyCreateView.as_view(),name='policies-create'),
	url(r'^policies/(?P<pk>\d+)/update$', views.PolicyUpdateView.as_view(),name='policies-update'),
	url(r'^policies/(?P<pk>\d+)/delete$', views.PolicyDeleteView.as_view(),name='policies-delete'),
	url(r'policies/detail/(?P<pk>[0-9]+)/$', views.PolicyDetailView.as_view(), name='policies-detail'),

	# Downloads
	url(r'^downloads/$', views.DownloadListView.as_view(), name='downloads-list'),
	url(r'^downloads/create$', views.DownloadCreateView.as_view(),name='downloads-create'),
	url(r'^downloads/(?P<pk>\d+)/update$', views.DownloadUpdateView.as_view(),name='downloads-update'),
	url(r'^downloads/(?P<pk>\d+)/delete$', views.DownloadDeleteView.as_view(),name='downloads-delete'),
	url(r'downloads/detail/(?P<pk>[0-9]+)/$', views.DownloadDetailView.as_view(), name='downloads-detail'),

	# Project
	url(r'^projects/$', views.ProjectListView.as_view(), name='projects-list'),
	url(r'^projects/create$', views.ProjectCreateView.as_view(),name='projects-create'),
	url(r'^projects/(?P<pk>\d+)/update$', views.ProjectUpdateView.as_view(),name='projects-update'),
	url(r'^projects/(?P<pk>\d+)/delete$', views.ProjectDeleteView.as_view(),name='projects-delete'),
	url(r'projects/detail/(?P<pk>[0-9]+)/$', views.ProjectDetailView.as_view(), name='projects-detail'),

	# Event
	url(r'^events/$', views.EventListView.as_view(), name='events-list'),
	url(r'^events/create$', views.EventCreateView.as_view(),name='events-create'),
	url(r'^events/(?P<pk>\d+)/update$', views.EventUpdateView.as_view(),name='events-update'),
	url(r'^events/(?P<pk>\d+)/delete$', views.EventDeleteView.as_view(),name='events-delete'),
	url(r'events/detail/(?P<pk>[0-9]+)/$', views.EventDetailView.as_view(), name='events-detail'),
	
	# News
	url(r'^news/$', views.NewsListView.as_view(), name='news-list'),
	url(r'^news/create$', views.NewsCreateView.as_view(),name='news-create'),
	url(r'^news/(?P<pk>\d+)/update$', views.NewsUpdateView.as_view(),name='news-update'),
	url(r'^news/(?P<pk>\d+)/delete$', views.NewsDeleteView.as_view(),name='news-delete'),
	url(r'news/detail/(?P<pk>[0-9]+)/$', views.NewsDetailView.as_view(), name='news-detail'),

	# HR
	url(r'^hr/$', views.HRListView.as_view(), name='hr-list'),
	url(r'^hr/sort$', views.HRSortView.as_view(),name='hr-sort'),
	url(r'^hr/create$', views.HRCreateView.as_view(),name='hr-create'),
	url(r'^hr/(?P<pk>\d+)/update$', views.HRUpdateView.as_view(),name='hr-update'),
	url(r'^hr/(?P<pk>\d+)/delete$', views.HRDeleteView.as_view(),name='hr-delete'),
	url(r'hr/detail/(?P<pk>[0-9]+)/$', views.HRDetailView.as_view(), name='hr-detail'),

	# Slider
	url(r'^sliders/$', views.SliderListView.as_view(), name='sliders-list'),
	url(r'^sliders/create$', views.SliderCreateView.as_view(),name='sliders-create'),
	url(r'^sliders/(?P<pk>\d+)/update$', views.SliderUpdateView.as_view(),name='sliders-update'),
	url(r'^sliders/(?P<pk>\d+)/delete$', views.SliderDeleteView.as_view(),name='sliders-delete'),
	url(r'sliders/detail/(?P<pk>[0-9]+)/$', views.SliderDetailView.as_view(), name='sliders-detail'),

	# Album
	url(r'^albums/$', views.AlbumListView.as_view(), name='albums-list'),
	url(r'^albums/create$', views.AlbumCreateView.as_view(),name='albums-create'),
	url(r'^albums/(?P<pk>\d+)/update$', views.AlbumUpdateView.as_view(),name='albums-update'),
	url(r'^albums/(?P<pk>\d+)/delete$', views.AlbumDeleteView.as_view(),name='albums-delete'),

	# AlbumPhoto
	url(r'^albums/(?P<album_pk>\d+)/photos/$', views.AlbumPhotoListView.as_view(), name='albums-photos-list'),
	url(r'^albums/(?P<album_pk>\d+)/photos/create$', views.AlbumPhotoCreateView.as_view(),name='albums-photos-create'),
	url(r'^albums/(?P<album_pk>\d+)/photos/(?P<pk>\d+)/update$', views.AlbumPhotoUpdateView.as_view(),name='albums-photos-update'),
	url(r'^albums/(?P<album_pk>\d+)/photos/(?P<pk>\d+)/delete$', views.AlbumPhotoDeleteView.as_view(),name='albums-photos-delete'),

	# Department
	url(r'^departments/$', views.DepartmentListView.as_view(), name='departments-list'),
	url(r'^departments/create$', views.DepartmentCreateView.as_view(),name='departments-create'),
	url(r'^departments/(?P<pk>\d+)/update$', views.DepartmentUpdateView.as_view(),name='departments-update'),
	url(r'^departments/(?P<pk>\d+)/delete$', views.DepartmentDeleteView.as_view(),name='departments-delete'),
	url(r'departments/detail/(?P<pk>[0-9]+)/$', views.DepartmentDetailView.as_view(), name='departments-detail'),

	# UsefulLink
	url(r'^useful-links/$', views.UsefulLinkListView.as_view(), name='useful-links-list'),
	url(r'^useful-links/create$', views.UsefulLinkCreateView.as_view(),name='useful-links-create'),
	url(r'^useful-links/(?P<pk>\d+)/update$', views.UsefulLinkUpdateView.as_view(),name='useful-links-update'),
	url(r'^useful-links/(?P<pk>\d+)/delete$', views.UsefulLinkDeleteView.as_view(),name='useful-links-delete'),
	url(r'useful-links/detail/(?P<pk>[0-9]+)/$', views.UsefulLinkDetailView.as_view(), name='useful-links-detail'),

	# Message
	url(r'^messages/$', views.MessageListView.as_view(), name='messages-list'),
	url(r'^messages/create$', views.MessageCreateView.as_view(),name='messages-create'),
	url(r'^messages/(?P<pk>\d+)/update$', views.MessageUpdateView.as_view(),name='messages-update'),
	url(r'^messages/(?P<pk>\d+)/delete$', views.MessageDeleteView.as_view(),name='messages-delete'),
	url(r'messages/detail/(?P<pk>[0-9]+)/$', views.MessageDetailView.as_view(), name='messages-detail'),

	# Page
	url(r'^pages/$', views.PageListView.as_view(), name='pages-list'),
	url(r'^pages/create$', views.PageCreateView.as_view(),name='pages-create'),
	url(r'^pages/(?P<pk>\d+)/update$', views.PageUpdateView.as_view(),name='pages-update'),
	url(r'^pages/(?P<pk>\d+)/delete$', views.PageDeleteView.as_view(),name='pages-delete'),
	url(r'pages/detail/(?P<pk>[0-9]+)/$', views.PageDetailView.as_view(), name='pages-detail'),

	# Navbar
	url(r'^navbar/$', views.NavbarListView.as_view(), name='navbar-list'),
	url(r'^navbar/sort$', views.NavbarSortView.as_view(), name='navbar-sort'),
	url(r'^navbar/create$', views.NavbarCreateView.as_view(),name='navbar-create'),
	url(r'^navbar/(?P<pk>\d+)/update$', views.NavbarUpdateView.as_view(),name='navbar-update'),
	url(r'^navbar/(?P<pk>\d+)/delete$', views.NavbarDeleteView.as_view(),name='navbar-delete'),
	url(r'navbar/detail/(?P<pk>[0-9]+)/$', views.NavbarDetailView.as_view(), name='navbar-detail'),


	# HomePagePopup
	url(r'^home-page-popup/$', views.HomePagePopupListView.as_view(), name='home-page-popup-list'),
	url(r'^home-page-popup/create$', views.HomePagePopupCreateView.as_view(),name='home-page-popup-create'),
	url(r'^home-page-popup/(?P<pk>\d+)/update$', views.HomePagePopupUpdateView.as_view(),name='home-page-popup-update'),
	url(r'^home-page-popup/(?P<pk>\d+)/delete$', views.HomePagePopupDeleteView.as_view(),name='home-page-popup-delete'),
	url(r'^home-page-popup/(?P<pk>[0-9]+)/detail/$', views.HomePagePopupDetailView.as_view(), name='home-page-popup-detail'),
	url(r'^home-page-popup/(?P<pk>\d+)/status-change$', views.HomePagePopupStatusChangeView.as_view(),name='home-page-popup-status-change'),

	# SiteConfig
	url(r'^site-config/$', views.SiteConfigListView.as_view(), name='site-config-list'),
	url(r'^site-config/update$', views.SiteConfigUpdateView.as_view(),name='site-config-update'),


	# List
	url(r'^list/$', views.ListListView.as_view(), name='list-list'),
	url(r'^list/create$', views.ListCreateView.as_view(),name='list-create'),
	url(r'^list/(?P<pk>\d+)/update$', views.ListUpdateView.as_view(),name='list-update'),

home/urls.py
from django.urls import path

from . import views
from api import views as api_view

urlpatterns = [

	path('', views.HomeView.as_view(), name='home'),

	#Album	  
	path('albums', views.AlbumsView.as_view(), name='album-list'),
	path('album/<int:pk>', views.AlbumDetailView.as_view(), name='album-detail'),

	# news
	path('news', views.NewsListView.as_view(), name='news-list'),
	path('news/<int:pk>', views.NewsDetailView.as_view(), name='news-detail'),

	# notices
	path('notices', views.NoticesListView.as_view(), name='notices-list'),
	path('notice/<int:pk>', views.NoticeDetailView.as_view(), name='notice-detail'),

	# press-releases
	path('press-releases', views.PressReleaseListView.as_view(), name='press-releases-list'),
	path('press-releases/<int:pk>', views.PressReleaseDetailView.as_view(), name='press-releases-detail'),

	# bids
	path('bids', views.BidListView.as_view(), name='bids-list'),
	path('bids/<int:pk>', views.BidDetailView.as_view(), name='bids-detail'),

	# downloads
	path('downloads', views.DownloadListView.as_view(), name='downloads-list'),
	path('downloads/<int:pk>', views.DownloadDetailView.as_view(), name='downloads-detail'),

	# publications
	path('publications', views.PublicationListView.as_view(), name='publications-list'),
	path('publications/<int:pk>', views.PublicationDetailView.as_view(), name='publications-detail'),

	# policies
	path('policies', views.PolicyListView.as_view(), name='policies-list'),
	path('policies/<int:pk>', views.PolicyDetailView.as_view(), name='policies-detail'),

	# events
	path('events', views.EventsListView.as_view(), name='events-list'),
	path('event/<int:pk>', views.EventDetailView.as_view(), name='event-detail'),

	# projects
	path('projects', views.ProjectsListView.as_view(), name='projects-list'),
	path('project/<int:pk>', views.ProjectDetailView.as_view(), name='project-detail'),

	# hr
	path('members', views.HRListView.as_view(), name='hr-list'),
	path('members/<int:pk>', views.HRDetailView.as_view(), name='hr-detail'),

	# pages
	path('pages/<str:slug>', views.PageDetailView.as_view(), name='pages-detail'),

	# useful links
	path('useful-links', views.UsefulLinkListView.as_view(), name='useful-links-list'),

	# message
	path('message', views.MessageCreateView.as_view(), name='message-create'),


	# list
	# path('list', views.ListListView.as_view(), name='list-list'),
	path('list/<int:pk>', views.ListDetailView.as_view(), name='list-detail'),
	path('list/<str:category>', views.ListListView.as_view(), name='list-category'),

	# api 
	path('api/notices', api_view.NoticeListApiView.as_view(), name='notices-api'),
]

dashboard/templates/dashboard/hr/detail.html
{% extends "dashboard/base/index.html" %} 

{% load static %}

{% block title %}{{ object.name }}{% endblock %}

{% block subtitle %}{{ object.name }}{% endblock %}

{% block head %}

{% endblock %} 

{% block content %}

<div class="mdk-header-layout__content mdk-header-layout__content--fullbleed mdk-header-layout__content--scrollable page">
    <div class="container-fluid page__container">
        <div class="card card-form form-header-layout">
            <div class="row no-gutters">
                <div class="col-lg-12">
                    <table class="table">
                        <tr>
                            <td>Name</td>
                            <td> : </td>
                            <td>{{ object.name }}</td>
                        </tr>
                        <tr>
                            <td>Position</td>
                            <td> : </td>
                            <td>{{ object.position | default_if_none:'' }}
                        </tr>
                        <tr>
                            <td>Level</td>
                            <td> : </td>
                            <td>{{ object.level | default_if_none:'' }}
                        </tr>
                        <tr>
                            <td>Photo</td>
                            <td> : </td>
                            <td><img src="{{ object.get_photo }}" alt="" style="height: 50px;"></td>
                        </tr>
                        <tr>
                            <td>Email</td>
                            <td> : </td>
                            <td>{{ object.email | default_if_none:'' }}
                        </tr>
                        <tr>
                            <td>Phone No.</td>
                            <td> : </td>
                            <td>{{ object.phone_no | default_if_none:'' }}
                        </tr>
                        <tr>
                            <td>Description</td>
                            <td> : </td>
                            <td>{{ object.description |safe}}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock content %}

dashboard/templates/dashboard/hr/form.html
{% extends "dashboard/base/index.html" %} 

{% load static %}

{% block title %}HR{% endblock %}

{% block subtitle %}HR{% endblock %}

{% block head %}

{% endblock %} 

{% block content %}
				<div class="mdk-header-layout__content mdk-header-layout__content--fullbleed mdk-header-layout__content--scrollable page">
					<div class="container-fluid page__container">
						<div class="card card-form form-header-layout">
							<h1>HR</h1>
							<div class="row no-gutters">
								<div class="col-lg-12 card-form__body card-body pomelo-form-card">
									<form method="post" action="" enctype="multipart/form-data" autocomplete="off" class="was-validated">
										{% csrf_token %}
							 			{% for field in form %}
										<div class="form-group" >
											<label>{{field.label}}{% if field.field.required %}* {% endif %}</label>
											{{ field }}
											<span style="color: red;">{{ field.errors }}</span>
										</div>
										{% endfor %}                                       
										<button type="submit" class="btn btn-primary"><i class="fa fa-check"></i> Submit</button>
									</form>
								</div>
							</div>
						</div>
					</div>
				</div>
{% endblock content %}


{% block script %}
	{% include "dashboard/base/form.html" %} 
{% endblock %}

dashboard/templates/dashboard/hr/list.html
{% extends "dashboard/base/index.html" %} 

{% load static %}

{% block title %}HR{% endblock %}

{% block subtitle %}HR{% endblock %}

{% block head %}


{% endblock %} 


{% block content %}

				<!-- Header Layout Content -->
				<div class="mdk-header-layout__content mdk-header-layout__content--fullbleed mdk-header-layout__content--scrollable page">
					<div class="container-fluid page__container">
						<div class="card document-card">
							<div class="row">
								<div class="col-md-12">
									<div style="text-align: right; margin-bottom: 35px;">
										<a href="{% url 'dashboard:hr-create' %}" class="btn btn-outline-primary" >
											<i class="fa fa-plus"></i>&nbsp; Add 
										</a>                                      
									</div>
								</div>
							</div>

							<div class="row">
								<div class="col-sm-12 document-table-space">
									
									<table class="table w-full no-footer" role="grid" >
										<thead class="table-space-top-bottom">
											<tr role="row">
												<th class="d-flex">
													<div style="flex: 1"></div>
													<div style="flex: 3">Name</div>
													<div style="flex: 3">Photo</div>
													<div style="flex: 3">Position</div>
													<div style="flex: 3">Level</div>
													<div style="flex: 3">Actions</div>
												</th>
											</tr>
										</thead>
										<tbody id="hrSortable">
									   		{% for object in object_list %}
											<tr style="width: 100%;" data-id="{{ object.pk }}">
												<td class="d-flex">
													<div style="flex: 1"><i class="fas fa-ellipsis-v"></i></div>
													<div style="flex: 3">{{ object.name }}</div>
													<div style="flex: 3"><img src="{{ object.get_photo }}" alt="" style="height: 50px;"></div>
													<div style="flex: 3">{{ object.position|default_if_none:'' }}</div>
													<div style="flex: 3">{{ object.level|default_if_none:'' }}</div>
													<div style="flex: 3">
														<div class="btn-group" role="group">
															<a href="{% url 'dashboard:hr-detail' object.pk %}" class="btn-sm btn btn-success btn-success-space " data-toggle="tooltip" data-original-title="Detail"><i
																class="fa fa-book"></i></a>
															<a href="{% url 'dashboard:hr-update' object.pk %}" class="btn-sm btn btn-info btn-success-space " data-toggle="tooltip" data-original-title="Modify">
																<i class="fa fa-pencil-alt"></i>
															</a>
															<a href="{% url 'dashboard:hr-delete' object.pk %}" class="btn-sm btn btn-danger a-delete" data-toggle="tooltip" data-original-title="Delete">
																<i class="far fa-trash-alt"></i>
															</a>
														</div>
													</div>
                                                </td>
                                            </tr>
											{% endfor %}   
                                        </tbody>
                                    </table>
                                </div>
                            </div>
							{% include "dashboard/base/pagination.html" %}
                        </div>
                    </div>
                </div>
                <!-- // END header-layout__content -->
{% endblock %}

{% block modal %}
{% endblock %}

{% block script %}
	<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
	<script type="text/javascript">
		$("#hrSortable").sortable({
			stop: function(event, ui){
				console.log('Sort done');
				var ids = [];
				$('#hrSortable').children().each( (index, element) => {
					ids.push($(element).data('id'));
				});
				console.log(ids);
				console.log(JSON.stringify(ids));
				$.get('{% url "dashboard:hr-sort" %}', {
					ids: JSON.stringify(ids),
				}, function(data, status){
					console.log(data, status);
				});
			}
		});
	</script>
{% endblock %}